name: coveralls

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install -U pip wheel
      - run: pip install -U pip wheel coverage
      - run: python --version
      - run: make coverage

      # Generate test coverage reports
      - run: coveralls
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
